Implement functional substitutions in rule applications
runtimeverification/proof-checker pull request #496
Opened 2023-11-22 19:02 UTC by MirceaS

2023-12-19 07:36 UTC, IljaZakharov approved these changes
Looks nice to me! I added a couple of comments, but they are minor, and we can address them in a separate PR because we will need to reuse the substitution logic in the `SimplificationInfo` class.

2023-12-19 07:36 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> +    @staticmethod
We can keep it as is, or we can make them just independent functions because we will need them also in the `SimplificationProver` class.

2023-12-19 07:36 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        ), f'The current configuration {str(self.current_configuration)} does not equal {str(lhs)}, the lhs of an instance of rule {str(rule.pattern)}'
I thought the `pretty` is preferable now, especially when the code is inside the proof expression.

2023-12-19 07:36 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        # Add the axioms/assumptions
This block for adding functional axioms should be possible to use in both `SimplificationProver` and `SimplificationPerformer`. But we can extract it later.

2023-12-19 07:36 UTC, IljaZakharov commented on generation/src/tests/unit/test_execution_proof_generation.py
> +# TODO: Add side conditions!
The function was moved to `test_kore_language_semantics`. It is called `rewrite_with_cells_config_pattern`.

2023-12-19 07:36 UTC, IljaZakharov commented on generation/src/tests/unit/test_kore_language_semantics.py
>              a_symbol = mod.symbol('a', sort, input_sorts=(sort,), is_functional=True, is_ctor=True)
It would be nice to have a separate function for checking assertions and doing functional substitutions, including adding functional axioms. We need the function in two classes. So it would be nice to have tests arranged correspondingly. But this can also be done in a separate PR as we will need to make other changes.

2023-12-19 07:36 UTC, IljaZakharov commented on generation/src/tests/unit/test_kore_language_semantics.py
> +            b_pe = ExecutionProofExp(sem, b)
Let's move it to the [test_kore_language_semantics.py](https://github.com/runtimeverification/proof-checker/pull/496/files#diff-e0683fa613aac0b14ad594d14cc30eb5fd3f1a6e367cde89cd4b6fd986ce46f3) as we use the `ExecutionProofExp` class. Another option is just to split the test.

2023-12-19 09:43 UTC, fiedlr requested changes
Let's not merge this until Nishant or I go over this, I want to doublecheck the proof sizes.

2023-12-19 15:33 UTC, MirceaS commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> -        raise KeyError(f'Variable name {name} not found in meta vars dict!')
I don't wanna keep around functions that are not used anywhere and are also untested. If we ever need it, it will be in the commit history.

2024-01-08 12:33 UTC, MirceaS commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        # TODO: Should we also check that the arguments are functional?
This will happen as part of a different PR

2024-01-08 12:59 UTC, MirceaS commented on generation/src/tests/unit/test_kore_language_semantics.py
> +            b_pe = ExecutionProofExp(sem, b)
Do you remember what you meant by this comment? Move what exactly?

2024-01-08 13:57 UTC, MirceaS commented on generation/src/proof_generation/k/execution_proof_generation.py
> +    @staticmethod
I'm not sure I get your point. If you can make a function static (that is, it does not depend on the state of a particular instance) then that's great. A function should only be given as little as it needs to do what it's supposed to do.

2024-01-08 14:45 UTC, MirceaS commented on generation/src/proof_generation/proofs/substitution.py
> +        )
Can you please elaborate on exactly what kind of test you mean?

2024-01-09 12:42 UTC, nishantjr commented on proofs/substitution.pretty-claim
> +Save
Ah, got it. Make sense.

2024-01-09 12:42 UTC, nishantjr commented on generation/src/proof_generation/proofs/substitution.py
> +        )
Add a unit test that passes in concrete proofs/axioms for each of the input proof thnks.

2024-01-09 12:42 UTC, nishantjr commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        ), f'The current configuration {str(self.current_configuration)} does not equal {str(lhs)}, the lhs of an instance of rule {str(rule.pattern)}'
Isn't this part of the `ExecutionProofExp` class? Please use `self.pretty(pattern)`

2024-01-09 12:42 UTC, nishantjr commented on proofs/generated-from-k/single-rewrite/foo-a.single-rewrite.pretty-proof
> +ModusPonens
@MirceaS This is a lot more than I expected to be in this proof.  The size of the binary proof has changed from 35 bytes to 12K. Any idea why there's so much more? Could you point me to all the changes that modify the main proof-generation.

2024-01-12 13:42 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        ), f'The current configuration {str(self.current_configuration)} does not equal {str(lhs)}, the lhs of an instance of rule {str(rule.pattern)}'
Agree with Nishant. It is not the same, you need to call self.pretty(self.current_configuration) and the rest similarly to keep notations pretty-printed.

2024-01-12 13:46 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        # Add the axioms/assumptions
There is a function stub `prove_substitutions` in the `SimplificationPerformer` above. It should do the same but for equational rules.

2024-01-12 13:51 UTC, fiedlr approved these changes
Looks good, Mircea. Please just fix the remaining comments.

2024-01-12 13:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/substitution.py
> +        )
I think we already have a test for this?

2024-01-12 13:51 UTC, fiedlr commented on generation/src/tests/unit/test_kore_language_semantics.py
>              a_symbol = mod.symbol('a', sort, input_sorts=(sort,), is_functional=True, is_ctor=True)
I agree, but since this is burning, let's do it in a follow-up. Could you guys pair up on this task together on Monday?

2024-01-12 13:51 UTC, fiedlr commented on generation/src/tests/unit/test_kore_language_semantics.py
> +            single_evar_krule = mod.rewrite_rule(kore_rewrites(sort.aml_symbol, EVar(0), EVar(0)))
What is this about? You cannot rewrite X to X without a symbol in Kore, can you?

2024-01-12 13:51 UTC, fiedlr commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +                assert isinstance(exists_var_pattern, EVar | SVar)
```suggestion
                assert isinstance(exists_var_pattern, EVar)
```

there is no existential binder for set variables in matching logic

2024-01-12 13:51 UTC, fiedlr commented on generation/src/proof_generation/k/execution_proof_generation.py
> +            # TODO: Get rid of this hack:
It's not a hack. Just a matter of whether doing it systematically from a single axiom will be cheaper

2024-01-12 14:03 UTC, MirceaS commented on generation/src/tests/unit/test_kore_language_semantics.py
> +            single_evar_krule = mod.rewrite_rule(kore_rewrites(sort.aml_symbol, EVar(0), EVar(0)))
This test is not meant to recreate rules that we see in practice. It is a test that ensures that appropriate functional axioms are created for a rewrite event.

2024-01-12 14:07 UTC, fiedlr commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        # Add the axioms/assumptions
I'll fix the `prove_subst` today

2024-01-12 14:12 UTC, MirceaS commented on generation/src/proof_generation/k/execution_proof_generation.py
> +            # TODO: Get rid of this hack:
I'm not sure I understand what you mean.
It is a hack since we're effectively adding as axioms multiple versions of a lemma which should be provable. Eventually we want to be able to, if not fully prove it, at least find a single form of the statement that we can then use to derive all the variations of it via alpha renaming.

2024-01-12 14:18 UTC, MirceaS commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +                assert isinstance(exists_var_pattern, EVar | SVar)
You're right. I just went by the comment.

2024-01-12 14:25 UTC, MirceaS commented on generation/src/proof_generation/proofs/substitution.py
> +def func_subst_axiom(forall_evar_name: int) -> Pattern:
We should really find a more systematic way to deal with notations that have variables in them. Having the definition take the bound variable as an input feels like we're going in the wrong direction. If that wasn't a thing then this wouldn't need to be a Notation. But for now, I suppose it would make things more efficient.

2024-01-12 14:38 UTC, MirceaS commented on generation/src/proof_generation/proofs/substitution.py
> +def func_subst_axiom(forall_evar_name: int) -> Pattern:
Actually, now that I think about how it's used I'm not so sure anymore that it should be a Notation. Its metavars are never instantiated. Its versions are just directly added as axioms, and then the metavars are instantiated when loading that axioms. So it never really acts as a Notation.

2024-01-12 15:17 UTC, fiedlr commented on generation/src/proof_generation/proofs/substitution.py
> +def func_subst_axiom(forall_evar_name: int) -> Pattern:
Ok, let's keep it like it is now.

2024-01-12 16:22 UTC, merged