Fix ZKLLVM and Lurk examples
runtimeverification/proof-checker pull request #619
Opened 2023-12-13 08:21 UTC by yzhang90

Part of #614

2023-12-13 17:39 UTC, Robertorosmaninho reviewed
A few comments about the way to display the numbers. Also, if we're not displaying the numbers for the CPU execution of Lurk CSL direct implementations due to current Lurk issues, we shouldn't display these numbers for the Pi2 implementations as well to be consistent.

2023-12-13 17:39 UTC, Robertorosmaninho commented on Performance.md
> +| transfer5000     |                0.823 |                38.842 |          |
Let's keep 3 places after the decimal point as a pattern

2023-12-13 17:39 UTC, Robertorosmaninho commented on Performance.md
> +| transfer5000*    |  505037 |            |              ∞ |               ∞ |              ∞ |
Same thing about keeping 3 places after the decimal point as a pattern

2023-12-13 17:39 UTC, Robertorosmaninho requested changes
See my comments above

2023-12-14 02:22 UTC, yzhang90 commented on Performance.md
> +| transfer5000     |                0.823 |                38.842 |          |
done

2023-12-14 02:22 UTC, yzhang90 commented on Performance.md
> +| transfer5000*    |  505037 |            |              ∞ |               ∞ |              ∞ |
done

2023-12-14 02:23 UTC, Robertorosmaninho commented
Just the last comment:
> ... Also, if we're not displaying the numbers for the CPU execution of Lurk CSL direct implementations due to current Lurk issues, we shouldn't display these numbers for the Pi2 implementations as well to be consistent.

2023-12-14 02:38 UTC, Robertorosmaninho approved these changes

2023-12-14 03:18 UTC, yzhang90 commented
> Just the last comment, @yzhang90:
> 
> > ... Also, if we're not displaying the numbers for the CPU execution of Lurk CSL direct implementations due to current Lurk issues, we shouldn't display these numbers for the Pi2 implementations as well to be consistent.

done

2023-12-14 03:44 UTC, merged