Implement `ExecutionProofExp.prove_lift_through_rewrite`
runtimeverification/proof-checker pull request #633
Opened 2023-12-15 05:55 UTC by malturki

WIP

2023-12-15 08:17 UTC, nishantjr commented on generation/src/proof_generation/proofs/kore.py
>  keq_next_substitution_axiom = Implies(
Did you mean to change this to `kore_implies`?

2023-12-15 08:17 UTC, nishantjr commented on generation/src/proof_generation/proofs/kore.py
> +keq_implication_axiom = Implies(
Same. Comment vs definition are different.

2023-12-18 11:13 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
>  keq_next_substitution_axiom = Implies(
No, this should be implies because MP will be applied.

2023-12-18 13:33 UTC, fiedlr requested changes
Looks good, Musab! Please fix the remaining issues I highlighted and add one unit test with a single instance. It didn't work probably because MP is being applied on `k->`. The rest is clear, sorts are kept throughout the implications.

2023-12-18 13:33 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +    kore_implies(
```suggestion
    Implies(
```

I think this should be `Implies`

2023-12-18 13:33 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +# (phi2:{phi0} k= phi3:{phi0}):{phi1} k-> ((phi5 k-> phi2):{phi4} k-> (phi5 k-> phi3):{phi4}):{phi6}
```suggestion
# (phi2:{phi0} k= phi3:{phi0}):{phi1} k-> ((phi5 k-> phi2):{phi4} -> (phi5 k-> phi3):{phi4})
```

2023-12-18 13:33 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +        # conclude: ((phi0 -> (next(phi1[p1/x])) k-> (phi0 -> next(phi1[p2/x]))))
```suggestion
        # conclude: ((phi0 k-> (next(phi1[p1/x])) -> (phi0 k-> next(phi1[p2/x]))))
```

2023-12-18 13:33 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +                {0: inner_sort, 1: outer_sort, 2: p1, 3: p2, 4: phi0, 5: outer_sort},  # Not sure what sort for 5!!
```suggestion
                {0: inner_sort, 1: outer_sort, 2: p1, 3: p2, 4: phi0, 5: outer_sort},  # Not sure what sort for 5!!
```

See my comment above, no sort needed, as this needs to be a normal implication for MP

2023-12-18 13:33 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +        imp_sort, imp_left, imp_right = kore_implies.assert_matches(imp.conc) # Not needed?
```suggestion
        _, _, _ = kore_implies.assert_matches(imp.conc) # Not needed?
```
Or use the corresponding method that just asserts but does not destruct

2023-12-18 13:33 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +        phi6,
```suggestion
```

2023-12-18 16:00 UTC, malturki commented on generation/src/proof_generation/proofs/kore.py
> +# (phi2:{phi0} k= phi3:{phi0}):{phi1} k-> ((phi5 k-> phi2):{phi4} k-> (phi5 k-> phi3):{phi4}):{phi6}
I suppose you meant that the topmost implication is not a kore_implies, right? So the comment should be:
```
(phi2:{phi0} k= phi3:{phi0}):{phi1} -> ((phi5 k-> phi2):{phi4} k-> (phi5 k-> phi3):{phi4}):{phi6}
                                   ^^^^
```
(which also means we would need `phi6` because kore_implies is sorted)

2023-12-18 16:03 UTC, malturki commented on generation/src/proof_generation/proofs/kore.py
>  keq_next_substitution_axiom = Implies(
Yes, the comment was incorrect. It looks like we will need to review the comments in this file (in a future PR) as there are currently similar issues in other definitions.

2023-12-18 16:09 UTC, malturki commented on generation/src/proof_generation/proofs/kore.py
> +# (phi2:{phi0} k= phi3:{phi0}):{phi1} k-> ((phi5 k-> phi2):{phi4} k-> (phi5 k-> phi3):{phi4}):{phi6}
Oh, nevermind. I see in your later comment that you expect both the outermost and the innermost implications not to be notations.

2023-12-18 16:17 UTC, malturki commented on generation/src/proof_generation/proofs/kore.py
> +        imp_sort, imp_left, imp_right = kore_implies.assert_matches(imp.conc) # Not needed?
This is actually not needed, but I kept it there while I was building the proof. It's been removed.

2023-12-18 19:04 UTC, malturki commented on generation/src/proof_generation/proofs/kore.py
> +        imp_sort, imp_left, imp_right = kore_implies.assert_matches(imp.conc) # Not needed?
Never mind. This became needed again after removing the extraneous parameters in this function. This is fixed in the latest commits.

2023-12-18 21:14 UTC, fiedlr approved these changes
Good job, Musab!

Two points:
a) We'll need to make a version that supports any hole `x`. But it's ok to suppose that it has id `0` for now, this is also done by `SimplificationPerformer`.
b) We can significantly simplify the proof with the refactorings proposed in https://github.com/orgs/runtimeverification/projects/47/views/1?pane=issue&itemId=47539153 
Even now, we can use `equality_with_subst` instead of adding the `keq_next...` axiom, but let's leave it like this for now since we will replace `equality_with_subst` with an even more general thing later.
c) I do not think we can reuse existing variables instead of having the matching on line 450, but let's leave it for now

2023-12-18 21:24 UTC, merged