Miscellaneous fixes and additions for the functional substitution work
runtimeverification/proof-checker pull request #666
Opened 2023-12-20 18:12 UTC by MirceaS

2023-12-20 23:05 UTC, fiedlr requested changes
Overall looks good, but I have questions,  please answer. Also please add tests for the `imp_match{l,r}` functions

2023-12-20 23:05 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
>  phi4 = MetaVar(4)
Maybe we could move these also to `aml`?

2023-12-20 23:05 UTC, fiedlr commented on generation/src/proof_generation/proofs/propositional.py
> +        actual_subst: dict[int, Pattern] = subst
Ditto

2023-12-20 23:05 UTC, fiedlr commented on generation/src/proof_generation/proofs/propositional.py
> +        actual_subst: dict[int, Pattern] = subst
Why this extra variable?

2023-12-20 23:05 UTC, fiedlr commented on generation/src/proof_generation/proofs/propositional.py
> +        actual_subst: dict[int, Pattern] = subst
The typing system should infer that `subst` is not `None` anymore when you call a function with it

2023-12-20 23:05 UTC, fiedlr commented on generation/src/proof_generation/proofs/propositional.py
> +        return self.dynamic_inst(h, actual_subst)
What if there are overlapping identifiers on the lhs?

2023-12-21 05:08 UTC, nishantjr commented on generation/src/proof_generation/proofs/propositional.py
> +        actual_subst: dict[int, Pattern] = subst
Perhaps we could put in a couple of tests for these?

2023-12-21 06:22 UTC, nishantjr commented on generation/src/proof_generation/proofs/propositional.py
> +        return self.dynamic_inst(h, actual_subst)
Perhaps we could put in a couple of tests for these , since we're worried about correcetness?

2023-12-21 13:06 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
>  phi4 = MetaVar(4)
We could do that, yeah.

2023-12-21 14:46 UTC, MirceaS commented on generation/src/proof_generation/proofs/propositional.py
> +        return self.dynamic_inst(h, actual_subst)
@fiedlr I'm not sure I understand what you mean. Identifiers overlapping with what?

2024-01-08 16:28 UTC, fiedlr approved these changes
LGTM.

2024-01-08 16:29 UTC, fiedlr commented on generation/src/proof_generation/proofs/propositional.py
> +        return self.dynamic_inst(h, actual_subst)
@MirceaS Nothing, I was just confused by one thing but it's clear to me now.

2024-01-08 17:04 UTC, merged