Preliminary definitions for kore functionality
runtimeverification/proof-checker pull request #681
Opened 2024-01-09 02:48 UTC by MirceaS

2024-01-09 11:40 UTC, nishantjr commented on generation/src/proof_generation/proofs/definedness.py
> +def functional(var: int = 0) -> Notation:
Lets remove this default. Its confusing otherwise.

2024-01-09 11:42 UTC, nishantjr approved these changes
Looks good, once suggestions applied.

2024-01-09 11:42 UTC, nishantjr commented on generation/src/proof_generation/proofs/kore.py
> +def sorted_forall(var: int) -> Notation:
Lets rename this to `kore_forall` for consistency.

2024-01-09 11:47 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +def sorted_forall(var: int) -> Notation:
`kore_forall` is defined below. `sorted_forall` and `kore_forall` are different, the same way that we already have `sorted_exists` and `kore_exists`. The `kore_` version is the `sorted` version limited to the appropriate outer sort.

2024-01-09 11:51 UTC, fiedlr requested changes

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/definedness.py
> +
Functional also needs to be `cached`

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +
@cache

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +
@cache

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +def kore_functional(var: int) -> Notation:
Can't we use `functional` here somehow?

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +    """kore_functional(var)(sort_of_pattern, outer_sort, pattern)"""
```suggestion
    """kore_functional(var)(inner_sort, outer_sort, pattern)"""
```

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +
`kore_equals` is missing the input and outer sort here

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +    """kore_is_function(arity)(sort_of_symbol, outer_sort, symbol)"""
```suggestion
    """kore_is_function(arity)(inner_sort, outer_sort, symbol)"""
```

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +def kore_is_function(arity: list[Pattern]) -> Notation:
```suggestion
def kore_is_function(arg_sorts: list[Pattern]) -> Notation:
```

2024-01-09 11:51 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +        notation_pattern = App(notation_pattern, EVar(index))
On very fast glance, I'm not sure what is is doing. Why App?

2024-01-09 11:53 UTC, nishantjr commented on generation/src/proof_generation/proofs/kore.py
> +def sorted_forall(var: int) -> Notation:
OK.

2024-01-09 11:57 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +def kore_functional(var: int) -> Notation:
Not really. ML `functional` uses a simple existential whereas kore `functional` has to use sorted existentials and kore equality instead.

2024-01-09 11:59 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +    """kore_functional(var)(sort_of_pattern, outer_sort, pattern)"""
`inner_sort` is very confusing imo. There are notations that have 0 or multiple "inner" sorts depending on which inner part you're looking at. I want to make it explicit that this has to be the sort of the pattern provided at the end.
The `inner_sort` terminology only really works for a few very simple constructs, like kore equality.

2024-01-09 11:59 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +    """kore_is_function(arity)(sort_of_symbol, outer_sort, symbol)"""
Ditto.

2024-01-09 12:05 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +        notation_pattern = App(notation_pattern, EVar(index))
Given a pattern `pat`, what this does is construct the pattern `forall x0. forall x1. ... forall xn. exists y. y = pat x0 x1 ... xn` where the x's are arguments to the (usually) symbol `pat`.
This is what being a function means.

2024-01-09 12:06 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +    return Notation('kore-function', 3, notation_pattern, 'is_kore_function({2}:{0}):{1}')
`kore_functional` also has `is` in the printed form. Do you want me to change that also?

2024-01-09 12:14 UTC, nishantjr commented on generation/src/proof_generation/proofs/kore.py
> +    """kore_functional(var)(sort_of_pattern, outer_sort, pattern)"""
Then lets do `return_sort`.

2024-01-09 12:17 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +    """kore_functional(var)(sort_of_pattern, outer_sort, pattern)"""
@nishantjr the "return" sort is the `outer_sort`, not inner. I think that one is named appropriately.

2024-01-09 12:21 UTC, nishantjr commented on generation/src/proof_generation/proofs/kore.py
> +    return Notation('kore-function', 3, notation_pattern, 'is_kore_function({2}:{0}):{1}')
Yes please, the names and the pretty printing should be consistent at the very least.

2024-01-09 12:22 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +    return Notation('kore-function', 3, notation_pattern, 'is_kore_function({2}:{0}):{1}')
What about keeping the `is` in all of them, since they're all predicates?

2024-01-11 10:11 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +    """kore_functional(var)(sort_of_pattern, outer_sort, pattern)"""
Let's be consistent, we use inner_sort with everywhere else. We can rename it in a different pr.

2024-01-11 10:11 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +    return Notation('kore-function', 3, notation_pattern, 'is_kore_function({2}:{0}):{1}')
Let's stick with what we have and worry about naming in a separate pr

2024-01-11 10:17 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +        notation_pattern = App(notation_pattern, EVar(index))
Aha, I see, not seeing a symbol was confusing

2024-01-11 10:18 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +    notation_pattern = kore_functional(len(arity))(phi0, phi1, notation_pattern)
```suggestion
    notation_pattern = kore_functional(len(arity) + 1)(phi0, phi1, notation_pattern)
```

since last `x` is `len(arity)`, `y` should start at `len(arity) + 1`

2024-01-11 10:19 UTC, fiedlr approved these changes
Looks good, Mircea, thanks. Just fix the bug with id indexing and do the renamings suggested by us. We can have a separate PR that fixes the naming to `is_` for predicates.

2024-01-11 10:24 UTC, fiedlr commented on generation/src/proof_generation/proofs/kore.py
> +    notation_pattern = MetaVar(2, e_fresh=tuple([EVar(x) for x in range(arg_len + 1)]))
```suggestion
    notation_pattern = MetaVar(2, e_fresh=tuple([EVar(x) for x in range(arg_len)]))
```

We want to have exactly `arg_len` of x's, which means this line as we start from 0 and go to `arg_len - 1`.

Then `y` will start at `arg_len` as you are using it in `kore_functional`

2024-01-11 14:58 UTC, MirceaS commented on generation/src/proof_generation/proofs/kore.py
> +    notation_pattern = MetaVar(2, e_fresh=tuple([EVar(x) for x in range(arg_len + 1)]))
What do you mean by `y`? EVars don't have string names, they just have integer id's. Only symbols have string names.
We need to account for the `arg_len` evars standing for the arguments as well as an extra one that is used to claim the functionality of the entire application.

2024-01-11 19:23 UTC, merged