Add a function to universally quantify axioms
runtimeverification/proof-checker pull request #710
Opened 2024-01-12 12:40 UTC by IljaZakharov

This PR currently just adds a method for getting quantified axioms, but it doesn't touch the pipeline for now.

2024-01-16 10:58 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        rewrite_step_proof = ExecutionProofExp.prove_substitutions(self, self.load_axiom(rule.pattern), substitution)
This renaming helped to avoid overlapping with the imported package having the same name.

2024-01-16 10:58 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> -    def prove_equality_from_rule(self, rule: proof.ProofThunk) -> proof.ProofThunk:
It appears to be a duplicate function from above,

2024-01-17 12:49 UTC, MirceaS requested changes

2024-01-17 12:49 UTC, MirceaS commented on generation/src/proof_generation/aml/syntax.py
> +        return self.subpattern.occurring_bound_vars().union({EVar(self.var)})
This name is misleading. `occuring_bound_vars` is not collecting bound variables that occur in the pattern. It is collecting the variables appearing in binders. `forall x. 1` has no bound variables but your function will still return `{x}`. I would rename it to `occuring_binder_vars`.

2024-01-17 12:56 UTC, IljaZakharov commented on generation/src/proof_generation/aml/syntax.py
> +        return self.subpattern.occurring_bound_vars().union({EVar(self.var)})
Agree! Applied.

2024-01-17 18:23 UTC, fiedlr approved these changes
I still didn't go over the tests, but overall looks pretty good! Please address the things I pointed out

2024-01-17 18:23 UTC, fiedlr commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        claim = gen_quantifiers_elimination(rule.pattern)
I guess we could have here the non-universally quantified version in `KRewritingRule` :-/ I know I contradict each other but this will be very expensive to do

2024-01-17 18:23 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +        Returns the set of all bound variables occurring in the pattern
```suggestion
        Returns the set of all variables occurring in some binder in the pattern
```

2024-01-17 18:23 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +        return self.pattern.occurring_binder_vars().difference({self.var}).union(self.plug.occurring_binder_vars())
```suggestion
        return self.pattern.occurring_binder_vars().union(self.plug.occurring_binder_vars())
```

The substitution only removes free occurrences of `self.var`, so we actually have to keep it because it might still be in some binder in either `pattern` or `plug`

2024-01-17 18:23 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +        return self.pattern.occurring_binder_vars().difference({self.var}).union(self.plug.occurring_binder_vars())
```suggestion
        return self.pattern.occurring_binder_vars().union(self.plug.occurring_binder_vars())
```

2024-01-17 18:23 UTC, fiedlr commented on generation/src/tests/unit/test_substitution.py
> +    assert gen_quantifiers_elimination(pattern) == expected
I guess we can keep this function in the codebase but I would try to avoid using it

2024-01-17 18:23 UTC, fiedlr commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        for name, plug in sorted(substitution.items(), key=lambda var: var[0]):
Very good catch!

2024-01-17 18:38 UTC, fiedlr approved these changes
Some more comments

2024-01-17 18:38 UTC, fiedlr commented on generation/src/proof_generation/proofs/substitution.py
> +    candidates = set(filter(lambda x: isinstance(x, EVar), phi.occurring_binder_vars()))
Shouldn't this be ordered? And it would try the candidates in this order

2024-01-18 09:51 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        claim = gen_quantifiers_elimination(rule.pattern)
OK, I'll extend the definition!

2024-01-18 09:51 UTC, IljaZakharov commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +            # TODO: Add an assertion that the variable is free
Got it, thank you!

2024-01-18 09:53 UTC, IljaZakharov commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +            self._inferred_notations.add(forall_notation)
I think we are safe as notations are frozen, and the attribute has the set type.

2024-01-18 09:55 UTC, IljaZakharov commented on generation/src/proof_generation/proofs/kore.py
>      _, requires, imp_right = kore_implies.assert_matches(pattern)
Hmm, makes sense!

2024-01-18 11:08 UTC, IljaZakharov commented on generation/src/proof_generation/aml/utils.py
>          raise NotImplementedError
I didn't get it. It is implemented at least partially and has tests.

2024-01-18 11:11 UTC, fiedlr commented on generation/src/proof_generation/aml/utils.py
>          raise NotImplementedError
I mean we can remove this occurrence in `utils.py`. It raises NotImplementedError, but this class extends `Pattern` which does the same with this function.

2024-01-18 11:11 UTC, IljaZakharov commented on generation/src/proof_generation/proofs/kore.py
>      _, requires, imp_right = kore_implies.assert_matches(pattern)
I just removed it because if we have an unquantified version in the krule, we don't need anything else.

2024-01-18 11:12 UTC, fiedlr commented on generation/src/proof_generation/k/execution_proof_generation.py
> +        claim = gen_quantifiers_elimination(rule.pattern)
Great!

2024-01-18 16:06 UTC, MirceaS approved these changes

2024-01-19 12:40 UTC, fiedlr commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +    raw_pattern: Pattern  # This shouldn't be used except for debugging
What is this about?

2024-01-19 12:45 UTC, fiedlr commented on generation/src/proof_generation/k/execution_proof_generation.py
> +                ), f'Attempting capturing substitution of {prover.pretty(var)} by {prover.pretty(plug)} in {prover.pretty(step_proof.conc)}'
Eventually we want this to be captured by one of those `apply_esubsts` above

2024-01-19 12:46 UTC, fiedlr commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +        return kl.matching_requires_substitution(requires)
Why this change? Can't we get the substitutions from the unquantified pattern as before?

2024-01-19 12:47 UTC, fiedlr commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +    def equational_rule(self, pattern: Pattern, free_vars_pattern: Pattern, raw_pattern: Pattern) -> KEquationalRule:
```suggestion
    def equational_rule(self, pattern: Pattern, unquantified_vars_pattern: Pattern, raw_pattern: Pattern) -> KEquationalRule:
```

2024-01-19 12:47 UTC, fiedlr commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +    def equational_rule(self, pattern: Pattern, free_vars_pattern: Pattern, raw_pattern: Pattern) -> KEquationalRule:
I would keep it consistent here

2024-01-19 12:59 UTC, fiedlr commented on generation/src/tests/unit/test_kore_language_semantics.py
> +            sem.rewrite_rule(kore_rewrites(cfg_sort, conf_before, conf_after))
What is this about?

2024-01-19 13:00 UTC, fiedlr commented on generation/src/tests/unit/test_kore_language_semantics.py
> +    scope._evars = {'varX': EVar(0), 'varY': EVar(1), 'varZ': EVar(2)}
What is this used for?

2024-01-19 15:06 UTC, fiedlr approved these changes
I conditionally approve so that it gets merged before new conflicts, but I need to have a look again on Monday.

2024-01-19 15:45 UTC, IljaZakharov commented on generation/src/proof_generation/proofs/substitution.py
> +    candidates = set(filter(lambda x: isinstance(x, EVar), phi.occurring_binder_vars()))
Applied!

2024-01-19 15:46 UTC, IljaZakharov commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +    raw_pattern: Pattern  # This shouldn't be used except for debugging
The `raw_pattern` is the original pattern extracted from `definition.kore`. We don't use it for now except in tests, but it also might be helpful for debugging to have the original pattern around.

2024-01-19 15:46 UTC, IljaZakharov commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +    raw_pattern: Pattern  # This shouldn't be used except for debugging
I'll rename it to the `original_pattern`.

2024-01-19 16:31 UTC, IljaZakharov commented on generation/src/proof_generation/k/execution_proof_generation.py
> +                ), f'Attempting capturing substitution of {prover.pretty(var)} by {prover.pretty(plug)} in {prover.pretty(step_proof.conc)}'
Agree, I'll make a separate issue on the board and add a _TODO_.

2024-01-19 16:32 UTC, IljaZakharov commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +        return kl.matching_requires_substitution(requires)
We need to call this function actually before we create the object, as it has changed patterns since the creation.

2024-01-19 16:33 UTC, IljaZakharov commented on generation/src/proof_generation/k/kore_convertion/language_semantics.py
> +    def equational_rule(self, pattern: Pattern, free_vars_pattern: Pattern, raw_pattern: Pattern) -> KEquationalRule:
Applied.

2024-01-19 16:35 UTC, IljaZakharov commented on generation/src/tests/unit/test_kore_language_semantics.py
> +            sem.rewrite_rule(kore_rewrites(cfg_sort, conf_before, conf_after))
Transformation of patterns happens in the semantics class. So it is easier now to call the semantics method to avoid further complications in tests.

2024-01-19 16:36 UTC, IljaZakharov commented on generation/src/tests/unit/test_kore_language_semantics.py
> +    scope._evars = {'varX': EVar(0), 'varY': EVar(1), 'varZ': EVar(2)}
Good catch. This is obsolete now.

2024-01-19 17:42 UTC, merged