Implement the can_be_replaced by function for MetaVars and associated helpers
runtimeverification/proof-checker pull request #722
Opened 2024-01-15 17:48 UTC by MirceaS

2024-01-17 16:49 UTC, IljaZakharov commented on generation/src/proof_generation/aml/syntax.py
> +    def svar_is_fresh(self, name: int) -> bool:
Why is it not implemented?

2024-01-17 17:36 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +    def svar_is_fresh(self, name: int) -> bool:
We agreed not to implement any functions that are not currently needed.

2024-01-17 18:45 UTC, fiedlr requested changes
Still did not finish, submitting what I have

2024-01-17 18:45 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +    def svar_is_fresh(self, name: int) -> bool:
We cannot have it implemented here and not in the `EVar`, for example. Either implement it nowhere or everywhere that it can be implemented without the `svar_is_app_ctx_hole`

2024-01-17 18:45 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +        return True
```suggestion
        raise NotImplementedError
```

2024-01-18 00:07 UTC, malturki approved these changes
Looks good to me

2024-01-18 12:28 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +    def svar_is_fresh(self, name: int) -> bool:
I guess we can remove the overriding occurrences too?

2024-01-18 12:32 UTC, MirceaS commented on generation/src/proof_generation/aml/syntax.py
> +    def svar_is_fresh(self, name: int) -> bool:
I don't think we should remove those. They stand there as a placeholder for the work that is to come.

2024-01-18 12:36 UTC, fiedlr requested changes

2024-01-18 12:36 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +            self.left.evar_is_fresh(name) and self.right.evar_is_app_ctx_hole(name)
One case is missing, where it's fresh on rhs and app_ctx on pjs

2024-01-18 12:36 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +        return (self.left.evar_is_app_ctx_hole(name) and self.right.evar_is_fresh(name)) or (
This line is incorrect. It would return true for two occurrences of var, but the occurrence has to be exactly one

2024-01-18 13:04 UTC, fiedlr commented on generation/src/proof_generation/aml/syntax.py
> +        return (self.left.evar_is_app_ctx_hole(name) and self.right.evar_is_fresh(name)) or (
Oops, I read it wrong. Sorry

2024-01-18 16:14 UTC, fiedlr approved these changes
Looks great! Thanks.

2024-01-18 16:28 UTC, merged