Pretty printing update
runtimeverification/proof-checker pull request #730
Opened 2024-01-16 17:25 UTC by fiedlr

2024-01-16 17:35 UTC, Robertorosmaninho commented on generation/src/proof_generation/interpreter/pretty_printing_interpreter.py
> +        self._print_stack()
Why call `_print_stack` here and below instead of `print_stack`?

2024-01-16 17:40 UTC, fiedlr commented on generation/src/proof_generation/interpreter/pretty_printing_interpreter.py
> +        self._print_stack()
Because I want to ignore the flag, so I just extracted the functionality I wanted

2024-01-16 17:41 UTC, fiedlr commented on generation/src/proof_generation/interpreter/pretty_printing_interpreter.py
> +        self._print_stack()
`print_stack()` is still used by the @pretty decorator. Basically if `pretty` flag is turned on, the stack should be  printed with every stack change

2024-01-16 17:42 UTC, Robertorosmaninho approved these changes
LGTM!

2024-01-16 17:42 UTC, Robertorosmaninho commented on generation/src/proof_generation/interpreter/pretty_printing_interpreter.py
> +        self._print_stack()
Got it! I just wanted to make sure that this was intentional!

2024-01-16 17:44 UTC, MirceaS requested changes

2024-01-16 17:44 UTC, MirceaS commented on proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
> +	1: (<ksym_Lbl'-LT-'generatedTop'-GT-'> <ksym_Lbl'-LT-'k'-GT-'> (ksym_inj(ksort_SortFoo, ksort_SortKItem, ksym_LblFooA'LParRParUnds'DOUBLE-REWRITE-SYNTAX'Unds'Foo()) ~> ksym_dotk()) </ksym_Lbl'-LT-'k
This implementation results in the Stack being printed on the same line as the `Publish` command, which is awkward. It also has the side effect that if we do enable stack printing, this stack for the `Publish` will be printed twice.
I think we should instead implement this by somehow figuring out that the instruction being processed in line 41 is a `Publish` and using this boolean information in the if on line 44 (of the pretty printing interpreter file).
We could have each function return this information as a boolean, since at the moment they're all just returning `None` anyway.

2024-01-16 17:46 UTC, fiedlr commented on proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
> +	1: (<ksym_Lbl'-LT-'generatedTop'-GT-'> <ksym_Lbl'-LT-'k'-GT-'> (ksym_inj(ksort_SortFoo, ksort_SortKItem, ksym_LblFooA'LParRParUnds'DOUBLE-REWRITE-SYNTAX'Unds'Foo()) ~> ksym_dotk()) </ksym_Lbl'-LT-'k
Not sure why it's awkward. Publish finishes a proof block. I want to see what state stack is in after finishing a proof block.

2024-01-16 17:48 UTC, fiedlr commented on proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
> +	1: (<ksym_Lbl'-LT-'generatedTop'-GT-'> <ksym_Lbl'-LT-'k'-GT-'> (ksym_inj(ksort_SortFoo, ksort_SortKItem, ksym_LblFooA'LParRParUnds'DOUBLE-REWRITE-SYNTAX'Unds'Foo()) ~> ksym_dotk()) </ksym_Lbl'-LT-'k
`print_stack` is a flag determining if `print_stack()` is even called. Then `print_stack()` checks if the flag is turned on.

2024-01-16 17:52 UTC, MirceaS commented on proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
> +	1: (<ksym_Lbl'-LT-'generatedTop'-GT-'> <ksym_Lbl'-LT-'k'-GT-'> (ksym_inj(ksort_SortFoo, ksort_SortKItem, ksym_LblFooA'LParRParUnds'DOUBLE-REWRITE-SYNTAX'Unds'Foo()) ~> ksym_dotk()) </ksym_Lbl'-LT-'k
`Publish Stack` sounds like a command that publishes the stack. It's confusing for a reader to see them both on the same line.
If we have that decorator, I propose the following: The decorator takes one more boolean argument: `force_print_stack`, set to `False` by default, which, when active, will print the stack regardless of the flag in the `pretty_options`. This should be easy to implement by having the `print_stack` take this `force_print_stack` argument as input.

2024-01-16 17:53 UTC, MirceaS commented on proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
> +	1: (<ksym_Lbl'-LT-'generatedTop'-GT-'> <ksym_Lbl'-LT-'k'-GT-'> (ksym_inj(ksort_SortFoo, ksort_SortKItem, ksym_LblFooA'LParRParUnds'DOUBLE-REWRITE-SYNTAX'Unds'Foo()) ~> ksym_dotk()) </ksym_Lbl'-LT-'k
This also means that we don't need to have two separate `print_stack` functions.

2024-01-16 17:56 UTC, fiedlr commented on proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
> +	1: (<ksym_Lbl'-LT-'generatedTop'-GT-'> <ksym_Lbl'-LT-'k'-GT-'> (ksym_inj(ksort_SortFoo, ksort_SortKItem, ksym_LblFooA'LParRParUnds'DOUBLE-REWRITE-SYNTAX'Unds'Foo()) ~> ksym_dotk()) </ksym_Lbl'-LT-'k
OK

2024-01-16 18:00 UTC, MirceaS commented on generation/src/proof_generation/interpreter/pretty_printing_interpreter.py
>      @pretty(print_stack=False)
modify this as well.
Also do we also want the stack printed for `publish_axiom`? Since that wasn`t there in the first iteration.

2024-01-16 18:01 UTC, fiedlr commented on generation/src/proof_generation/interpreter/pretty_printing_interpreter.py
>      @pretty(print_stack=False)
That was a bug, fixed

2024-01-16 18:01 UTC, fiedlr commented on proofs/generated-from-k/double-rewrite/foo-a.double-rewrite.pretty-claim
> +	1: (<ksym_Lbl'-LT-'generatedTop'-GT-'> <ksym_Lbl'-LT-'k'-GT-'> (ksym_inj(ksort_SortFoo, ksort_SortKItem, ksym_LblFooA'LParRParUnds'DOUBLE-REWRITE-SYNTAX'Unds'Foo()) ~> ksym_dotk()) </ksym_Lbl'-LT-'k
How about now?

2024-01-16 18:06 UTC, MirceaS commented
With the risk of sounding a bit pedantic, I wouldn't name the new variable `ignore_pretty_opts` because to me that suggests that we're ignoring what the opts say and instead just fall back on what the other decorator argument says, which is not what's happening. The `ignore` variable forces the stack to be printed no matter what. But I'll leave this decision up to you.

On that note however, I would change the decorator calls so that if we set the `ignore` flag, we don't also set the original flag, since it's irellevant, and it could be confusing to have them both (since the `ignore` one takes precedence).

2024-01-16 18:13 UTC, MirceaS commented
> With the risk of sounding a bit pedantic, I wouldn't name the new variable `ignore_stack_opts` because to me that suggests that we're ignoring what the opts say and instead just fall back on what the other decorator argument says, which is not what's happening. The `ignore` variable forces the stack to be printed no matter what. But I'll leave this decision up to you.
> 
> On that note however, I would change the decorator calls so that if we set the `ignore` flag, we don't also set the original flag, since it's irellevant, and it could be confusing to have them both (since the `ignore` one takes precedence).

Alternatively, you could change the logic so that the variable does what I said in my interpretation, which would also allow us to never print the stack for certain commands, even if the user enables the stack printing option.

2024-01-16 20:14 UTC, malturki reviewed
Why not just set `print_stack=True` for `publish_proof` and `publish_claim` (without adding any extra flags)? Wouldn't this achieve the intended behavior?

2024-01-17 07:40 UTC, fiedlr commented
> Why not just set `print_stack=True` for `publish_proof` and `publish_claim` (without adding any extra flags)? Wouldn't this achieve the intended behavior?

No, because we have a CLI flag we want to bypass. Only setting it to true would not show the stack for publish with the flag turned on

2024-01-17 07:46 UTC, fiedlr commented
> With the risk of sounding a bit pedantic, I wouldn't name the new variable `ignore_stack_opts` because to me that suggests that we're ignoring what the opts say and instead just fall back on what the other decorator argument says, which is not what's happening. The `ignore` variable forces the stack to be printed no matter what. But I'll leave this decision up to you.
> 
> 
> 
> On that note however, I would change the decorator calls so that if we set the `ignore` flag, we don't also set the original flag, since it's irellevant, and it could be confusing to have them both (since the `ignore` one takes precedence).

I'll rename it to call_print_stack and force_stack

For the ordering thing, that's not really true.

Simply having force_stack=True does not show the stack because the print function isn't called

2024-01-17 13:12 UTC, MirceaS approved these changes

2024-01-17 22:03 UTC, merged