Introducing pi2 script
runtimeverification/proof-checker pull request #746
Opened 2024-01-18 13:22 UTC by Robertorosmaninho

Closes #685 

- [x] Check-Proof Script
- [ ] Gen-Proof Script
- [ ] Gen-Hints Script
- [ ] Kompile Script

2024-01-22 09:52 UTC, IljaZakharov requested changes
Looks good, great job! 

But I have a number of suggestions to make it shine:
- It is unclear where to find instructions for installing backends and where is the location of supported K files. Both top-level and pi2 README files require improvements. 
- I would propose using `.build`directory by default if a user doesn't specify any output directories.
- Some scripts unexpectedly crash (see my comments) or I failed to find them in the path at all. 
- Please use our default formatting and type checking for the Python code.
- I left a couple of really minor coding suggestions for working with paths and options.

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/README.md
> +kompile <definition.k>
Personally, I don't like the fact that scripts pollute the current directory by default. We have places for both definition and hints in `.build`. I find it useful because one always knows where to find files, and they don't appear in git.

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/README.md
> +gen-hint <kompiled-dir> <input.kore> -o <hint>
It also returned nothing for the `--help` argument.

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/README.md
> +check-proof <zk-backend> <proof-directory>
`check-proof -a` just crashed.

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/README.md
> +Have a working K installation with the appropriate version.
What about ZK backends?

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/pi2/check_proof.py
> +    script_name = "./check_with_" + zk_backend + ".sh"
Let's use `os.path` or `pathlib` for working with files and paths.

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/pi2/check_proof.py
> +    arguments = []
Is there any way just to forward these arguments without going through all of them? I know it is possible with `argparse`, but I never worked with `click`.

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/pi2/gen_hints.py
> +    cmd = "where" if platform.system() == "Windows" else "which"
We definitely want to rely on some library for such matters. One of `distutils` or `shutils`.

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/pi2/gen_hints.py
> +    script_name = "gen-execution-proof-hints.sh"
Same about working with paths.

2024-01-22 09:52 UTC, IljaZakharov commented on pi2/pi2/gen_hints.py
> +    cmd = "where" if platform.system() == "Windows" else "which"
And I doubt that we support Windows at all.

2024-01-22 19:37 UTC, Robertorosmaninho commented on pi2/pi2/check_proof.py
> +    arguments = []
It isn't because `click` has its way to parse variables through the CLI, by already setting them as arguments to the main program.

2024-01-22 19:37 UTC, Robertorosmaninho commented on pi2/README.md
> +check-proof <zk-backend> <proof-directory>
Fixed

2024-01-22 19:37 UTC, Robertorosmaninho commented on pi2/README.md
> +gen-hint <kompiled-dir> <input.kore> -o <hint>
sorry, the correct command is `gen-hints`

2024-01-22 19:37 UTC, Robertorosmaninho commented on pi2/README.md
> +gen-hint <kompiled-dir> <input.kore> -o <hint>
Please be sure you installed the pi2 project and its using the correct environment either by `poetry shell -C pi2` or `source ${path_of_virtual_env}`
Ex.:
```bash
$ poetry shell -C pi2
Virtual environment already activated: /Users/robertorosmaninho/Library/Caches/pypoetry/virtualenvs/pi2-ubaZfU4E-py3.11
$ gen-hints --help
Usage: gen-hints [OPTIONS] [KOMPILED_DIR] [INPUT_KORE]

Options:
  -o, --output TEXT  Save the generated into into FILENAME. Default is INPUT-
                     KORE.hints.
  -v, --verbose      Show verbose output.
  --help             Show this message and exit.
```

I'll add this information to the `README.md`

2024-01-22 19:37 UTC, Robertorosmaninho commented on pi2/README.md
> +pi2 <definition.k> <input.kore> [OPTIONS]
We can call it `program_input.kore` or something like that, just to be clear that:
1. The program is the input for the given definition (workflow and gramma inherit from K)
2. Make it clear that the script and our workflow expect a `KORE` file.

About "where to find K definitions", I can add the path that contains our examples on `README.md`, but the idea is that people will bring "their own" K definition and KORE input.

2024-01-22 19:37 UTC, Robertorosmaninho commented on pi2/pi2/gen_hints.py
> +    script_name = "gen-execution-proof-hints.sh"
This is just the name of the script, the path that may be an issue is below

2024-01-22 19:41 UTC, Robertorosmaninho commented on pi2/README.md
> +kompile <definition.k>
I agree with you if we consider ourselves as the main users of this script. However, if we think of a user outside of RV who will use this tool in his/her own workflow, the default output directory being a hidden folder on our directory doesn't seem intuitive.

2024-01-25 17:42 UTC, Robertorosmaninho commented
Hey @IljaZakharov, I think I solved most, if not all, of your comments and added the `-d/--default-directory` flag to all scripts so they can use the `.build` directory to output their results!

2024-01-25 17:45 UTC, IljaZakharov approved these changes
Looks nice, thank you!

2024-01-26 13:43 UTC, merged