Update zkllvm instructions
runtimeverification/proof-checker pull request #765
Opened 2024-01-22 08:50 UTC by yzhang90

Closes #760

2024-01-22 12:32 UTC, Robertorosmaninho requested changes

2024-01-22 12:32 UTC, Robertorosmaninho commented on zkllvm/README.md
> +python3 translator.py <path-to-binar-input-dir>
`path-to-binary-inputs-dir`

2024-01-22 12:32 UTC, Robertorosmaninho commented on Performance.md
>  | svm-goal            |             585.308 |                     ∞ |
We should try to generate numbers for the other examples as well! For sure they will be better as well!

2024-01-22 12:57 UTC, yzhang90 commented on zkllvm/README.md
> +python3 translator.py <path-to-binar-input-dir>
done

2024-01-24 02:04 UTC, yzhang90 commented on Performance.md
>  | svm-goal            |             585.308 |                     ∞ |
done

2024-01-24 02:07 UTC, Robertorosmaninho approved these changes
Thanks! LGTM!
The gain we get on Circuit generation with it is quite impressive.

2024-01-24 03:52 UTC, merged